server:
  port: 8082

spring:
    application:
        name: ms-demo
    ############## MySQL DB Configuration ##############
    datasource:
        url: jdbc:mysql://localhost:3306/springbootdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin_sayak25
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    
review:
  service:
    base-url: http://localhost:8083 # Base URL for the review service

vendor:
  service:
    base-url: http://localhost:8081 # Base URL for the vendor service
#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ms-demo:${server.port}
    hostname: localhost


